"""Generate publication-ready LaTeX table for ANOVA variance decomposition.

Reads data/anova_variance_results.tsv (generated by loss_variance_analysis.py)
and prints a formatted LaTeX table showing the percentage of variance explained
by each factorial term (Amount, Modulation Type, Feature, Source, 2-Way Interactions,
and Higher-Order / Residual), with Bonferroni-corrected significance asterisks displayed
to the right of the percentages.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Union

import pandas as pd

# Method mappings and ordering
HUMAN_ROW = ("human", "Human Listeners")

METHOD_GROUPS = [
    [
        ("mss_log_lin", "MSS Log + Lin."),
        ("mss_rev", "MSS Revisited"),
        ("mfcc", "MFCC"),
    ],
    [
        ("scat1d_log1p", "Scat1D"),
        ("jtfs_log1p", "JTFS"),
    ],
    [
        ("vggish", "VGGish"),
        ("encodec48k", "EnCodec 48~kHz"),
        ("clap2", "MS-CLAP"),
        ("panns_wavegram_logmel", "PANNs WGLM"),
    ],
]

LOSS_FN_ALIASES = {
    "scat1d": "scat1d_log1p",
    "jtfs": "jtfs_log1p",
    "encodec": "encodec48k",
    "encodec48": "encodec48k",
    "encodec24k": "encodec48k",
    "clap": "clap2",
    "panns_wglm": "panns_wavegram_logmel",
}


def format_sig_figs(val: float, precision: int) -> str:
    """Format a float to a fixed number of significant figures, padding trailing zeros."""
    if val is None or pd.isna(val):
        return ""
    s = f"{val:.{precision}g}"
    if "e" in s or "E" in s:
        return f"{val:.{precision}f}"
    parts = s.split(".")
    if len(parts) == 1:
        needed = precision - len(parts[0])
        return parts[0] + "." + "0" * max(0, needed)
    sig_digits = (
        len(parts[1].lstrip("0"))
        if parts[0] == "0"
        else len(parts[0].lstrip("0")) + len(parts[1])
    )
    needed = precision - sig_digits
    if needed > 0:
        s += "0" * needed
    return s


def format_percentage(val: float, sig_digits: int) -> str:
    """Format a float percentage to fixed significant figures followed by \\%."""
    if val is None or pd.isna(val):
        return ""
    return f"{format_sig_figs(val, sig_digits)}\\%"


def get_asterisks(p_val: float) -> str:
    """Return LaTeX significance asterisks based on p-value."""
    if p_val is None or pd.isna(p_val):
        return ""
    if p_val < 0.001:
        return "$^{***}$"
    elif p_val < 0.01:
        return "$^{**}$"
    elif p_val < 0.05:
        return "$^{*}$"
    return ""


def extract_variance_data(sub_df: pd.DataFrame, sig_digits: int) -> dict[str, tuple[str, str]]:
    """Extract variance percentage and asterisk for each table column."""
    t_map = dict(zip(sub_df["Source"], sub_df["pct_var"]))
    p_map = dict(zip(sub_df["Source"], sub_df["p_bonf"]))

    two_way_pct = sum(v for k, v in t_map.items() if ":" in k)
    higher_order_pct = t_map.get("Residual (pooled)", 0.0)

    return {
        "amount": (
            format_percentage(t_map.get("rating_stimulus", 0.0), sig_digits),
            get_asterisks(p_map.get("rating_stimulus")),
        ),
        "mod": (
            format_percentage(t_map.get("modulation", 0.0), sig_digits),
            get_asterisks(p_map.get("modulation")),
        ),
        "feat": (
            format_percentage(t_map.get("feature", 0.0), sig_digits),
            get_asterisks(p_map.get("feature")),
        ),
        "source": (
            format_percentage(t_map.get("source", 0.0), sig_digits),
            get_asterisks(p_map.get("source")),
        ),
        "two_way": (
            format_percentage(two_way_pct, sig_digits),
            "",  # No asterisk for composite 2-way interactions
        ),
        "higher_order": (
            format_percentage(higher_order_pct, sig_digits),
            "",  # No asterisk for residual / higher-order interactions
        ),
    }


def format_row(method_name: str, var_data: dict[str, tuple[str, str]]) -> str:
    """Format a single table row with method, 4 tested columns (val + ast), and 2 center columns."""
    tested_cols = ["amount", "mod", "feat", "source"]
    parts = [f"    {method_name:<18s}"]
    for col in tested_cols:
        val, ast = var_data[col]
        val_pad = f"{val:>9s}"
        ast_pad = f"{ast:<8s}" if ast else " " * 8
        parts.append(f"& {val_pad} & {ast_pad}")

    # Last two columns are center aligned without asterisks
    for col in ["two_way", "higher_order"]:
        val, _ = var_data[col]
        val_pad = f"{val:>8s}"
        parts.append(f"& {val_pad}")

    return " ".join(parts) + " \\\\"


def generate_latex_table(df: pd.DataFrame, sig_digits: int = 3) -> str:
    """Generate the complete LaTeX table string from ANOVA results dataframe."""
    df = df.copy()
    if "loss_fn" in df.columns:
        df["canonical_loss"] = df["loss_fn"].map(lambda x: LOSS_FN_ALIASES.get(x, x))

    lines = []
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{")
    lines.append(
        r"ANOVA variance decomposition of human listening study responses and audio distance representations. "
        r"Variance components ($\sigma$) indicate the percentage of total variance explained by each factorial term: "
        r"modulation amount, modulation type, acoustic feature, sound source, two-way interaction terms, and "
        r"higher-order residual variance. Statistical significance for main factors is indicated by asterisks "
        r"based on Bonferroni-corrected $p$-values ($^{*}p < 0.05$, $^{**}p < 0.01$, $^{***}p < 0.001$; unstarred indicates $p \ge 0.05$)."
    )
    lines.append(r"}")
    lines.append(r"\label{tab:anova_variance_decomposition}")
    lines.append(r"\vspace{3pt}")
    lines.append(r"\sisetup{")
    lines.append(r"    round-pad = true,")
    lines.append(r"    reset-text-series=false, ")
    lines.append(r"    text-series-to-math=true, ")
    lines.append(r"    mode=text,")
    lines.append(r"    tight-spacing=false,")
    lines.append(r"    separate-uncertainty=false,")
    lines.append(r"    detect-weight=true,")
    lines.append(r"    detect-inline-weight=math,")
    lines.append(r"}")
    lines.append(r"\setlength{\tabcolsep}{4.5pt}")
    lines.append(r"\begin{tabular}{")
    lines.append(r"    l")
    for _ in range(4):
        lines.append(r"    r @{\,} l")
    lines.append(r"    c")
    lines.append(r"    c")
    lines.append(r"}")
    lines.append(r"    \toprule")
    lines.append(
        r"    \textbf{Method} "
        r"& \multicolumn{2}{c}{$\sigma\text{ (Amount)}$} "
        r"& \multicolumn{2}{c}{$\sigma\text{ (Mod. Type)}$} "
        r"& \multicolumn{2}{c}{$\sigma\text{ (Feature)}$} "
        r"& \multicolumn{2}{c}{$\sigma\text{ (Source)}$} "
        r"& $\sigma\text{ (2-way Inter.)}$ "
        r"& $\sigma\text{ (Higher Order)}$ \\"
    )
    lines.append(r"    \midrule")

    # Row 1: Human listening study benchmark
    human_match = df[df["canonical_loss"] == HUMAN_ROW[0]]
    if human_match.empty:
        human_match = df[df["loss_fn"] == HUMAN_ROW[0]]
    if not human_match.empty:
        human_data = extract_variance_data(human_match, sig_digits)
        lines.append(format_row(HUMAN_ROW[1], human_data))
        lines.append(r"    \midrule")

    # Model rows grouped
    for g_idx, group in enumerate(METHOD_GROUPS):
        if g_idx > 0:
            lines.append(r"    \addlinespace[5pt]")
        for canon_key, display_name in group:
            m_match = df[df["canonical_loss"] == canon_key]
            if m_match.empty:
                m_match = df[df["loss_fn"] == canon_key]
            if m_match.empty:
                continue
            m_data = extract_variance_data(m_match, sig_digits)
            lines.append(format_row(display_name, m_data))

    lines.append(r"    \bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")

    return "\n".join(lines)


def resolve_file_path(path_str: str) -> Path:
    """Resolve file path relative to current working dir, repo root, or script location."""
    p = Path(path_str).expanduser()
    if p.exists():
        return p.resolve()
    repo_root = Path(__file__).resolve().parent.parent.parent
    candidate = (repo_root / path_str).resolve()
    if candidate.exists():
        return candidate
    candidate_script = (Path(__file__).resolve().parent / path_str).resolve()
    if candidate_script.exists():
        return candidate_script
    return p.resolve()


def main():
    parser = argparse.ArgumentParser(
        description="Print LaTeX ANOVA variance decomposition table from anova_variance_results.tsv to terminal."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="data/anova_variance_results.tsv",
        help="Path to anova_variance_results.tsv (default: data/anova_variance_results.tsv)",
    )
    parser.add_argument(
        "--sig-digits",
        "--sig-figs",
        type=int,
        default=3,
        dest="sig_digits",
        help="Number of significant figures for variance percentages (default: 3).",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Optional path to save generated LaTeX table to a .tex file.",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Suppress printing to terminal (useful when exporting only to file).",
    )
    args = parser.parse_args()

    input_path = resolve_file_path(args.input)
    if not input_path.exists():
        sys.stderr.write(f"Error: ANOVA variance results file not found at: {input_path}\n")
        sys.exit(1)

    sep = "\t" if input_path.suffix in [".tsv", ".txt"] else ","
    df = pd.read_csv(input_path, sep=sep)

    table_latex = generate_latex_table(df, sig_digits=args.sig_digits)

    if not args.quiet:
        print(table_latex)

    if args.output:
        out_path = Path(args.output).expanduser().resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(table_latex, encoding="utf-8")
        sys.stderr.write(f"Table successfully written to: {out_path}\n")


if __name__ == "__main__":
    main()
